"""Initial migration

Revision ID: 27da7be76afe
Revises: a0a812491ec8
Create Date: 2024-05-19 14:27:51.588891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27da7be76afe'
down_revision: Union[str, None] = 'a0a812491ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_user_fkey', 'roles', type_='foreignkey')
    op.drop_column('roles', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('roles_user_fkey', 'roles', 'users', ['user'], ['id'])
    # ### end Alembic commands ###
