"""Battlepower role can be null

Revision ID: 77780377ab7c
Revises: 27da7be76afe
Create Date: 2024-05-19 14:31:48.116647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77780377ab7c'
down_revision: Union[str, None] = '27da7be76afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'battlepower_role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'battlepower_role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
