"""Initial migration

Revision ID: a0a812491ec8
Revises: 368896e3d52c
Create Date: 2024-05-19 14:25:01.726946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a812491ec8'
down_revision: Union[str, None] = '368896e3d52c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'battlepower_role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'battlepower_role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
