name: Python Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can specify the version of Python you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Tesseract
      run: |
        sudo apt-get update
        sudo apt-get install -y wget lsb-release
        wget https://github.com/tesseract-ocr/tesseract/archive/refs/tags/5.3.4.zip
        sudo apt-get install -y unzip
        unzip 5.3.4.zip
        cd tesseract-5.3.4
        sudo apt-get install -y automake ca-certificates g++ git libtool libleptonica-dev make pkg-config
        ./autogen.sh
        ./configure
        make
        sudo make install
        sudo ldconfig

    - name: Run tests
      run: |
        python -m unittest discover -s tests
