name: Python Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can specify the version of Python you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Tesseract
      run: |
        sudo add-apt-repository ppa:alex-p/tesseract-ocr5
        sudo apt update
        sudo apt install tesseract-ocr

    - name: Run tests
      run: |
        python -m unittest discover -s tests
